---
- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - nginx_controller_license
    - nginx_controller_auth_token
    - nginx_controller_fqdn

- name: PUT NGINX Controller license
  uri:
    url: "https://{{ nginx_controller_fqdn }}/{{ nginx_controller_api_version }}/platform/license"
    method: PUT
    body:
      metadata:
        name: license
      desiredState:
        content: "{{ nginx_controller_license }}"
    body_format: json
    return_content: true
    status_code:
      - 200
      - 202
    validate_certs: "{{ nginx_controller_validate_certs | default(false) }}"
    headers:
      Cookie: "{{ nginx_controller_auth_token }}"
  register: nginx_controller_response

- name: GET NGINX Controller license status
  uri:
    url: "https://{{ nginx_controller_fqdn }}/{{ nginx_controller_api_version }}/platform/license"
    method: GET
    status_code: 200
    validate_certs: "{{ nginx_controller_validate_certs | default(false) }}"
    headers:
      Cookie: "{{ nginx_controller_auth_token }}"
  register: nginx_controller_license
